image:
  name: docker:latest

services: 
  - docker:dind

before_script:  
  - docker info
  - echo "$DOCKER_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY

stages:
- build-and-push

Build & Push Docker Image:
  stage: build-and-push
  image: docker:dind
  script:
  - docker build --tag $DOCKER_USERNAME/alpine-with-terraform .
  - docker push $DOCKER_USERNAME/alpine-with-terraform .  