image:
  name: docker:latest

services: 
  - docker:dind

before_script:  
  - docker info
  - docker login --username "$DOCKER_USERNAME" \
                 --password "$DOCKER_TOKEN" # git-lab-token

stages:
- build
- deploy

Build Docker Image:
  stage: build
  image: docker:dind
  script:
  - docker build --tag johnmorsley/alpine-with-terraform .